# Generated by Django 3.1.4 on 2020-12-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_auto_20201222_0727'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplicant',
            unique_together={('job_id', 'applicant_email_id')},
        ),
    ]
